# Generated by Django 4.0.4 on 2022-05-13 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pollss', '0002_produkty'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produkty',
            new_name='Sklepik',
        ),
    ]
