# Generated by Django 4.0.4 on 2022-05-25 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pollss', '0005_enrollment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='student',
            new_name='Student',
        ),
    ]
