# Generated by Django 4.0.4 on 2022-05-25 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pollss', '0006_rename_student_enrollment_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='enrollment',
            new_name='Zapisy',
        ),
    ]
