# Generated by Django 4.0.4 on 2022-05-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollss', '0008_alter_kurs_students'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Zapisy',
            new_name='Enrollment',
        ),
        migrations.AlterField(
            model_name='kurs',
            name='students',
            field=models.ManyToManyField(to='pollss.student'),
        ),
    ]
