# Generated by Django 4.0.4 on 2022-05-25 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollss', '0009_rename_zapisy_enrollment_alter_kurs_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kurs',
            name='students',
            field=models.ManyToManyField(through='pollss.Enrollment', to='pollss.student'),
        ),
    ]
