# Generated by Django 4.0.4 on 2022-05-25 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollss', '0010_alter_kurs_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kurs',
            name='students',
            field=models.ManyToManyField(to='pollss.student'),
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
